// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBckpH-y-7VpDo-MaOY4usg_BUn0ZnR2Hs',
    appId: '1:777930591719:web:4523dec896db5e9570c142',
    messagingSenderId: '777930591719',
    projectId: 'feed-5e17e',
    authDomain: 'feed-5e17e.firebaseapp.com',
    storageBucket: 'feed-5e17e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1uVlf4lc6sd49vs7KF0HlVd_rPqQ7yTo',
    appId: '1:777930591719:android:3b84a81f9adbcd6970c142',
    messagingSenderId: '777930591719',
    projectId: 'feed-5e17e',
    storageBucket: 'feed-5e17e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtEE8ykKB82ZOJ8vmQuG8lFW7E4mVf9QM',
    appId: '1:777930591719:ios:1b6e286c7852782870c142',
    messagingSenderId: '777930591719',
    projectId: 'feed-5e17e',
    storageBucket: 'feed-5e17e.appspot.com',
    androidClientId: '777930591719-1bpeosnccfsn816ppslbub0nilregjk6.apps.googleusercontent.com',
    iosClientId: '777930591719-etn86mmme2hcrraprtnq8lnepc7fujg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.feed',
  );
}
